### PR TITLE
Fixing shutdown routine

### LINKED ISSUE #30: Shutdown routine
I noticed that server responses with an error to the `shutdown` request:

```
01:04:47.884 DEBUG l.core.MessageReader - Received headers: Content-Length: 59
01:04:47.884 DEBUG l.core.Connection - Received {"jsonrpc":"2.0","id":14,"method":"shutdown","params":null}
01:04:47.900 DEBUG l.core.MessageWriter - Content-Length: 199
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":{"meaning":"Invalid method parameter(s).","error":{"obj":[{"msg":["command parameters must be given"],"args":[]}]}}},"id":14}
01:04:47.900 DEBUG l.core.MessageWriter - payload: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":{"meaning":"Invalid method parameter(s).","error":{"obj":[{"msg":["command parameters must be given"],"args":[]}]}}},"id":14}
```

`shutdown` request is not supposed to have any parameters, so I think that the underlying LSP library doesn't handle it well.

It causes some extra lags in Atom (https://github.com/atom/atom-languageclient/issues/119) and I suspect after this response server never receives an `exit` request. By the way, I didn't find how `exit` is handled in the server.

### PR DESCRIPTION
**Pull request by laughedelic**
Fixes #30 

The problem is in the scala-json-rpc way of handling commands (requests) and notifications. It doesn't allow them to have an empty or absent `params` key:

https://github.com/dhpcs/scala-json-rpc/blob/c25cda4b6a39441bbe4ce25f57ab88e3db5ef635/scala-json-rpc/src/main/scala/com/dhpcs/jsonrpc/MessageCompanions.scala#L66-L71

While the [LSP spec for `shutdown`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown-request) says explicitly:

> Request:
> * method: 'shutdown'
> * params: void

Same about `shutdown` response and `exit` notification. These are the only messages in LSP that don't have parameters, so I'm adding a special `read`override to handle these messages.

### CODE REVIEW

File: metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala [hunk 1]
```diff
@@ -282,7 +282,8 @@ class ScalametaLanguageServer(
     } catch {
       case NonFatal(e) =>
         onError(e)
-        ShutdownResult(-1)
+        // FIXME: server shouldn't send shutdown response if there was no shutdown request
+        ShutdownResult()
```
Comment (laughedelic) [inline metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala]: @olafurpg I think something wrong is happening here. Server shouldn't send a shutdown response on completion request failure.

Comment (olafurpg) [reply metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala]: lol, no idea how that go there. feel free to remove the whole try/catch, errors get caught and logged on request now.

Comment (laughedelic) [reply metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala]: Done in f3d9342 (+ same in `documentFormattingRequest`)

**Comment by laughedelic** [comment]
Oh no... 😭  CI release is broken again. Didn't trigger on merge. 
I wonder if that condition is too complicated for Travis, because the [docs say](https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A):

> `condition`: deploy when a single bash condition evaluates to `true`. This must be a string value, and is equivalant to `if [[ <condition> ]]; then <deploy>; fi`. For example, `$CC = gcc`.
