### PR TITLE
Use _CURSOR_ in signatureHelp

### LINKED ISSUE #65: Use _CURSOR_ for signatureHelp
signatureHelp currently uses completions, which can often fail with a string index out of bounds error. This can be fixed by inserting _CURSOR_ in the right place before invoking completions, as we did in #64 .

### PR DESCRIPTION
**Pull request by gabro**
Fixes #65

### CODE REVIEW

File: metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala [hunk 1]
```diff
@@ -16,7 +16,7 @@ object SignatureHelpProvider extends LazyLogging {
       global = compiler,
       code = cursor.contents,
       filename = cursor.uri,
-      cursor = None
+      cursor = Some(cursor.offset + 1)
```
Comment (gabro) [inline metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala]: `offset + 1` because we want

```
Predef.assert(_CURSOR_
```

and not

```
Predef.assert_CURSOR_(
```

Comment (olafurpg) [reply metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala]: Did you check if this changed/improved the behavior anywhere?

Comment (gabro) [reply metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala]: Honestly, no. I just made sure all tests still pass (and the first one didn't without the `+ 1`

Comment (olafurpg) [reply metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala]: Sounds good, I will keep my eyes open for what effect this has, maybe it's not as important for signatureHelp as I thought it would be
